### ISSUE TITLE
Centerlines missing in train and validation precomputed features

### ISSUE THREAD

**Issue by stratomaster31** [jagjeet-singh/argoverse-forecasting#2]
Hi there,

Thank you for sharing the baselines and setting up the benchmark!

I've noticed that, in the train/val sets of pre-computed features:

     "candidate_centerlines" -> array of nones
     "oracle_centerlines" --> ok!

But in the test set:

     "candidate_centerlines" ->ok!
     "oracle_centerlines" -->  array of nones

Is this intended, and if so, why?

**Comment by jagjeet-singh** [comment]
Hi,
This is intended.
In train/val set, you have access to the entire 5 secs of the trajectory. Hence, you can compute oracle centerline and don't need candidate centerlines. For test set, you just have access to the first 2 secs. As such, you can only hypothesize candidate centerlines.

**Comment by stratomaster31** [comment]
Hi, thank you for the response.

It makes sense....  So, for the ledearboard, how many guesses have to be included for each sample? Exactly 6 or >=6? In case of >=6, how the six guesses are taken from the total number of guesses for each sample?

**Comment by jagjeet-singh** [comment]
You can include as many guesses as you want. 
For K=6, we take the first 6 guesses. Similarly for K=3 and K=1. So sort your guesses based on the confidence

**Comment by stratomaster31** [comment]
ok! everything is clear now!

**Comment by jagjeet-singh** [comment]
Happy to help!
