### ISSUE TITLE
How to get the object class for the forecasting data?

### ISSUE THREAD

**Issue by PhyllisH** [jagjeet-singh/argoverse-forecasting#9]
Hi~ In the argoverse-downloading page, I saw that object classes are annotated in the 3D tracking challenge while in the motion forecasting phase, the object classes are not included. Would there be any method to get the object classes in the forecasting challenge? Could you provide the tracking_id to the object class mapping profile?

Best regards,

Phyllis

**Comment by jagjeet-singh** [comment]
Hi, object classes are not available in the current version of Argoverse. But we are considering the possibility of including those in subsequent releases. Stay tuned!
